# -*- coding: utf-8 -*-
"""Jeds80M.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MGkabGltlu2xcqXWbZZQGZtBdzlCe0hK
"""

#Jeds ATM assignment
print("Thank you for choosing Bank of Jed")
#setting da pin and initial values
pin = int(input("Enter your 4-digit pin: "))
balance = 0
withdraw = 0
deposit = 0
choice = None
run = True
#most of everything is found in this while
while run == True:
  if pin > 9999:
    print("Your pin must be 4 digits!! Like are you stupid!!")
  choice = input("Would you like to deposit, withdraw, stop, or see your balance: ")
  if choice == "deposit":
    deposit = int(input("How much money are you trying to deposit (I don't expect a lot): "))
  elif choice == "withdraw":
    withdraw = int(input("How much money are you going to withdraw: "))
  elif choice == "balance":
    print(f"Your balance is {balance} $")
  elif choice == "stop":
    break
    print("I can't believe I have to tell you that's an invalid choice")
#Yk i gotta check if deposit and withdraw are not None before subtracting
  if deposit is not None and withdraw is not None:
    balance = deposit - withdraw